// Safe to edit by hand
// =============================================================================
// Which botanical each page's share card carries (2026-09-30)
// =============================================================================
// Which botanical a page's share card carries (BaseLayout passes the first of
// doodlesForPage() to the card spec). Until 2026-10-01 the same map also
// placed faint botanicals in page sections (src/scripts/ambient-doodles.ts,
// removed). Pure data and functions, unit tested in doodle-map.test.ts.
//
// The drawings are generated by `npm run doodles` (scripts/doodles.config.mjs)
// into src/assets/doodles/.
// =============================================================================

/** Every doodle the generator writes. Keep in step with scripts/doodles.config.mjs. */
export const DOODLE_NAMES = ['olive-sprig', 'eucalyptus', 'berry-sprig', 'leafy-stem'] as const;

export type DoodleName = (typeof DOODLE_NAMES)[number];

/**
 * First path segment -> the botanical a page's share card carries. The olive
 * sprig (her Instagram signature) opens Home and About; the rest just vary so
 * two pages rarely open alike.
 */
export const PAGE_DOODLES: Record<string, DoodleName> = {
  '': 'olive-sprig',
  about: 'olive-sprig',
  services: 'eucalyptus',
  process: 'eucalyptus',
  'e-design': 'leafy-stem',
  contact: 'berry-sprig',
  faq: 'leafy-stem',
  portfolio: 'berry-sprig',
};

/** The order the rest of the set follows. */
const ROTATION: DoodleName[] = ['berry-sprig', 'eucalyptus', 'olive-sprig', 'leafy-stem'];

/** The first segment of a path: "/services/" -> "services", "/" -> "". */
export function firstSegment(path: string): string {
  const clean = (path.split(/[?#]/)[0] ?? '').replace(/^\/+|\/+$/g, '');
  return clean.split('/')[0] ?? '';
}

/** A stable small number from a string (FNV-1a). */
function hashOf(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}

/**
 * The doodles for `count` sections of the page at `path`: the page's own
 * first, then the rotation from a page-specific starting point, skipping any
 * that would repeat the one before. Same page, same doodles, every build.
 */
export function doodlesForPage(path: string, count: number): DoodleName[] {
  const seg = firstSegment(path);
  const first = PAGE_DOODLES[seg] ?? ROTATION[hashOf(seg) % ROTATION.length]!;
  const out: DoodleName[] = [];
  let k = hashOf(`${seg}#`) % ROTATION.length;
  for (let i = 0; i < count; i++) {
    if (i === 0) {
      out.push(first);
      continue;
    }
    let next = ROTATION[k % ROTATION.length]!;
    k++;
    if (next === out[i - 1]) {
      next = ROTATION[k % ROTATION.length]!;
      k++;
    }
    out.push(next);
  }
  return out;
}
