// Safe to edit by hand
// =============================================================================
// Which doodle belongs to which page (2026-09-30)
// =============================================================================
// The doodles are small ink drawings of things from a designer's table,
// generated by `npm run doodles` (scripts/doodles.config.mjs) into
// src/assets/doodles/. This file only decides WHERE they appear. Pure data
// and one function, unit tested in doodle-map.test.ts.
//
// A page's doodle shows on the paper card that drops under its link in the
// desktop header. Change a line in PAGE_DOODLES to swap one. A custom page
// Staci builds (any address not listed) gets the vase of branches.
// =============================================================================

/** Every doodle the generator writes. Keep in step with scripts/doodles.config.mjs. */
export const DOODLE_NAMES = [
  'olive-sprig',
  'pendant',
  'table-lamp',
  'armchair',
  'vase-stems',
  'arched-mirror',
  'coffee-mug',
  'book-stack',
] as const;

export type DoodleName = (typeof DOODLE_NAMES)[number];

/**
 * First path segment -> doodle. About is the olive sprig (Staci's own
 * Instagram motif); Services hangs a pendant over the price list; Process
 * pulls up a chair; E-Design is the lamp you'd work by at home; Contact is the
 * coffee a consultation starts with; FAQ is the stack where the answers live.
 */
export const PAGE_DOODLES: Record<string, DoodleName> = {
  about: 'olive-sprig',
  services: 'pendant',
  process: 'armchair',
  'e-design': 'table-lamp',
  contact: 'coffee-mug',
  faq: 'book-stack',
  portfolio: 'arched-mirror',
};

/** The first segment of a path: "/services/" -> "services", "/" -> "". */
export function firstSegment(path: string): string {
  const clean = (path.split(/[?#]/)[0] ?? '').replace(/^\/+|\/+$/g, '');
  return clean.split('/')[0] ?? '';
}

/** The doodle for a page address (a nav href). */
export function doodleForPath(path: string): DoodleName {
  return PAGE_DOODLES[firstSegment(path)] ?? 'vase-stems';
}
