/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProcessStep = {
  _id: string;
  _type: "processStep";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stepNumber?: number;
  title?: string;
  timeEstimate?: string;
  shortDescription?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  features?: Array<string>;
  tierNote?: string;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: string;
  priceNumeric?: number;
  shortDescription?: string;
  features?: Array<string>;
  bestFor?: string;
  longDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  displayOrder?: number;
  showOnHomepage?: boolean;
  ctaLabel?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PhilosophyPoint = {
  _id: string;
  _type: "philosophyPoint";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  displayOrder?: number;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h4";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?: "Pricing & Cost" | "The Process" | "Logistics" | "Service Area" | "Getting Started";
  displayOrder?: number;
  alsoShowOnProcessPage?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  email?: string;
  phone?: string;
  availabilityStatus?: string;
  serviceAreas?: Array<string>;
  travelFees?: Array<{
    distanceLabel?: string;
    fee?: string;
    _type: "travelFeeTier";
    _key: string;
  }>;
  socialInstagram?: string;
  socialFacebook?: string;
  footerCredit?: string;
};

export type CtaBlock = {
  _type: "ctaBlock";
  label?: string;
  linkType?: "internal" | "external" | "email" | "phone";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homePage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "aboutPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "processPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "servicesPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "faqPage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "contactPage";
  };
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  formIntroNote?: string;
  whatToExpectHeadline?: string;
  whatToExpectContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  schedulingLink?: string;
  schedulingLinkLabel?: string;
  availabilityNote?: string;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  categoryOrder?: Array<string>;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  servicesListHeadline?: string;
  servicesListSubhead?: string;
  builderRealtorSection?: {
    eyebrow?: string;
    headline?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    forBuildersText?: string;
    forRealtorsText?: string;
    forContractorsText?: string;
    cta?: CtaBlock;
  };
  serviceAreaSection?: {
    eyebrow?: string;
    headline?: string;
    description?: string;
  };
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
};

export type ProcessPage = {
  _id: string;
  _type: "processPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  faqSectionEyebrow?: string;
  faqSectionHeadline?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  storyEyebrow?: string;
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  staciPhoto?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  staciAttribution?: string;
  backgroundLine?: string;
  serviceAreaMention?: string;
  philosophyEyebrow?: string;
  philosophyHeadline?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroPrimaryCta?: CtaBlock;
  heroSecondaryCta?: CtaBlock;
  meetStaciPhoto?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  meetStaciHeadline?: string;
  meetStaciContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  meetStaciCta?: CtaBlock;
  processPreviewEyebrow?: string;
  processPreviewHeadline?: string;
  processPreviewCta?: CtaBlock;
  featuredTestimonial?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "testimonial";
  };
  testimonialsEyebrow?: string;
  testimonialsHeadline?: string;
  testimonialsToShow?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "testimonial";
  }>;
  servicesGridEyebrow?: string;
  servicesGridHeadline?: string;
  servicesGridSubhead?: string;
  servicesGridCta?: CtaBlock;
  serviceAreaCue?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  date?: string;
  source?: "Facebook" | "Google" | "Houzz" | "Direct (email or text)" | "Other";
  featured?: boolean;
  relatedProject?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "project";
  };
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  location?: string;
  roomType?: "livingRoom" | "bedroom" | "kitchen" | "diningRoom" | "office" | "wholeHome" | "multipleRooms" | "other";
  year?: number;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  briefSummary?: string;
  introStory?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  beforeAfters?: Array<{
    beforeImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    afterImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    caption?: string;
    _type: "beforeAfterPair";
    _key: string;
  }>;
  servicesUsed?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "service";
  }>;
  relatedTestimonial?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "testimonial";
  };
  displayOrder?: number;
  publishedAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ProcessStep | Service | Slug | PhilosophyPoint | FaqItem | SiteSettings | CtaBlock | ContactPage | FaqPage | ServicesPage | ProcessPage | AboutPage | SanityImageCrop | SanityImageHotspot | HomePage | Testimonial | Project | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
