/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ShopCollectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "shopCollection";
};

export type ShopItem = {
  _id: string;
  _type: "shopItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  vendor?: string;
  affiliateUrl?: string;
  note?: string;
  collection?: ShopCollectionReference;
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ShopCollection = {
  _id: string;
  _type: "shopCollection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  blurb?: string;
  orderRank?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type PressItem = {
  _id: string;
  _type: "pressItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  outlet?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  quote?: string;
  url?: string;
  date?: string;
  orderRank?: string;
};

export type JournalCategory = {
  _id: string;
  _type: "journalCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type ProcessStep = {
  _id: string;
  _type: "processStep";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stepNumber?: number;
  title?: string;
  timeEstimate?: string;
  shortDescription?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  features?: Array<string>;
  tierNote?: string;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  orderRank?: string;
};

export type PhilosophyPoint = {
  _id: string;
  _type: "philosophyPoint";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  displayOrder?: number;
  orderRank?: string;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h4";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?:
    | "Pricing & Cost"
    | "The Process"
    | "Logistics"
    | "Service Area"
    | "Getting Started";
  displayOrder?: number;
  alsoShowOnProcessPage?: boolean;
};

export type StudioPlaybook = {
  _id: string;
  _type: "studioPlaybook";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  guides?: Array<{
    title?: string;
    summary?: string;
    sections?: Array<{
      heading?: string;
      tone?: "default" | "primary" | "positive" | "caution";
      body?: string;
      bullets?: Array<string>;
      links?: Array<{
        label?: string;
        url?: string;
        _type: "playbookLink";
        _key: string;
      }>;
      _type: "playbookSection";
      _key: string;
    }>;
    _type: "playbookGuide";
    _key: string;
  }>;
};

export type StudioNotes = {
  _id: string;
  _type: "studioNotes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessSummary?: string;
  idealClient?: string;
  voiceSummary?: string;
  wordsToAvoid?: Array<string>;
};

export type StudioGuide = {
  _id: string;
  _type: "studioGuide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guideTitle?: string;
  guideIntro?: string;
  studioMap?: Array<{
    area?: string;
    description?: string;
    _type: "mapRow";
    _key: string;
  }>;
  howTos?: Array<{
    title?: string;
    steps?: Array<string>;
    _type: "howTo";
    _key: string;
  }>;
  tips?: Array<{
    heading?: string;
    tone?: "default" | "primary" | "caution" | "positive";
    body?: string;
    _type: "tip";
    _key: string;
  }>;
};

export type BudgetCalculator = {
  _id: string;
  _type: "budgetCalculator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  introEyebrow?: string;
  introHeadline?: string;
  introSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  rooms?: Array<{
    label?: string;
    baseLow?: number;
    baseHigh?: number;
    _type: "room";
    _key: string;
  }>;
  scopeOptions?: Array<{
    label?: string;
    addLow?: number;
    addHigh?: number;
    _type: "scopeOption";
    _key: string;
  }>;
  addOns?: Array<{
    label?: string;
    low?: number;
    high?: number;
    _type: "addOn";
    _key: string;
  }>;
  resultCopy?: string;
  disclaimer?: string;
  ctaLabel?: string;
  consultPriceNote?: string;
};

export type LeadMagnetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "leadMagnet";
};

export type StyleQuiz = {
  _id: string;
  _type: "styleQuiz";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  introEyebrow?: string;
  introHeadline?: string;
  introSubhead?: string;
  introImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  questions?: Array<{
    prompt?: string;
    helpText?: string;
    answers?: Array<{
      label?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      };
      archetypeWeights?: Array<{
        archetypeSlug?: string;
        weight?: number;
        _type: "archetypeWeight";
        _key: string;
      }>;
      _type: "quizAnswer";
      _key: string;
    }>;
    _type: "quizQuestion";
    _key: string;
  }>;
  qualifiers?: Array<{
    prompt?: string;
    type?: "budget" | "timeline" | "room";
    options?: Array<{
      label?: string;
      value?: string;
      _type: "qualifierOption";
      _key: string;
    }>;
    _type: "qualifier";
    _key: string;
  }>;
  archetypes?: Array<{
    name?: string;
    slug?: Slug;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    images?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }>;
    recommendedServiceRef?: ServiceReference;
    resultCtaLabel?: string;
    _type: "archetype";
    _key: string;
  }>;
  gate?: {
    mode?: "optional" | "required-for-bonus" | "required";
    heading?: string;
    blurb?: string;
    consentNote?: string;
    espTag?: string;
  };
  routing?: {
    highIntentRule?: string;
    bookCtaLabel?: string;
    guideCtaLabel?: string;
    guideRef?: LeadMagnetReference;
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type LeadMagnet = {
  _id: string;
  _type: "leadMagnet";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  gateHeading?: string;
  gateBlurb?: string;
  buttonLabel?: string;
  successMessage?: string;
  espTag?: string;
  seoTitle?: string;
  seoDescription?: string;
  published?: boolean;
  orderRank?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: string;
  priceNumeric?: number;
  shortDescription?: string;
  features?: Array<string>;
  bestFor?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  longDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  displayOrder?: number;
  showOnHomepage?: boolean;
  ctaLabel?: string;
  orderRank?: string;
};

export type PressPage = {
  _id: string;
  _type: "pressPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  intro?: string;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ResourcesPage = {
  _id: string;
  _type: "resourcesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  intro?: string;
  cards?: Array<{
    title?: string;
    blurb?: string;
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    link?: string;
    _type: "resourceCard";
    _key: string;
  }>;
};

export type GiftPage = {
  _id: string;
  _type: "giftPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  intro?: string;
  options?: Array<{
    label?: string;
    amount?: string;
    blurb?: string;
    _type: "giftOption";
    _key: string;
  }>;
  howItWorks?: Array<{
    stepNumber?: number;
    title?: string;
    body?: string;
    _type: "giftStep";
    _key: string;
  }>;
  finePrint?: string;
  ctaLabel?: string;
};

export type ShopPage = {
  _id: string;
  _type: "shopPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  enabled?: boolean;
  intro?: string;
  disclosure?: string;
  collections?: Array<
    {
      _key: string;
    } & ShopCollectionReference
  >;
};

export type FaqItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqItem";
};

export type EDesignPage = {
  _id: string;
  _type: "eDesignPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  howItWorks?: Array<{
    stepNumber?: number;
    title?: string;
    body?: string;
    _type: "howItWorksStep";
    _key: string;
  }>;
  whatsIncluded?: Array<string>;
  tiers?: Array<{
    name?: string;
    price?: string;
    priceNumeric?: number;
    features?: Array<string>;
    bestFor?: string;
    ctaLabel?: string;
    _type: "eDesignTier";
    _key: string;
  }>;
  faqRefs?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type ProcessPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "processPage";
};

export type ServicesPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "servicesPage";
};

export type FaqPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type JournalPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalPage";
};

export type JournalEntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalEntry";
};

export type CtaBlock = {
  _type: "ctaBlock";
  label?: string;
  linkType?: "internal" | "external" | "email" | "phone";
  internalLink?:
    | HomePageReference
    | AboutPageReference
    | ProcessPageReference
    | ServicesPageReference
    | FaqPageReference
    | ContactPageReference
    | JournalPageReference
    | JournalEntryReference;
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type NotFoundPage = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  eyebrow?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaHref?: string;
};

export type PortfolioPage = {
  _id: string;
  _type: "portfolioPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  email?: string;
  phone?: string;
  availabilityStatus?: string;
  serviceAreas?: Array<string>;
  travelFees?: Array<{
    distanceLabel?: string;
    fee?: string;
    _type: "travelFeeTier";
    _key: string;
  }>;
  socialInstagram?: string;
  socialFacebook?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  footerCredit?: string;
  footerCreditUrl?: string;
  newsletter?: {
    enabled?: boolean;
    providerLabel?: string;
    formActionUrl?: string;
    audienceId?: string;
    heading?: string;
    blurb?: string;
    buttonLabel?: string;
    successMessage?: string;
    consentNote?: string;
  };
  googleBusinessUrl?: string;
  reviewsNote?: string;
  sectionVisibility?: {
    showPortfolio?: boolean;
    showJournal?: boolean;
    showShop?: boolean;
    showEDesign?: boolean;
    showGiftCertificates?: boolean;
    showPress?: boolean;
    showResources?: boolean;
    showGuides?: boolean;
    showStyleQuiz?: boolean;
    showBudgetCalculator?: boolean;
  };
  satisfactionGuarantee?: string;
};

export type JournalCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalCategory";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type JournalEntry = {
  _id: string;
  _type: "journalEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & JournalCategoryReference
  >;
  author?: string;
  publishedAt?: string;
  updatedAt?: string;
  featured?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "lead" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              openInNewTab?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              vendor?: string;
              url?: string;
              _type: "sourcedFrom";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        size?: "standard" | "wide" | "full";
        _type: "inlineImage";
        _key: string;
      }
    | {
        quote?: string;
        attribution?: string;
        _type: "pullQuote";
        _key: string;
      }
    | {
        beforeImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        afterImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _type: "beforeAfter";
        _key: string;
      }
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        itemName?: string;
        vendor?: string;
        price?: string;
        url?: string;
        notes?: string;
        _type: "sourceCard";
        _key: string;
      }
    | {
        label?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet";
          markDefs?: Array<{
            href?: string;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "tipCallout";
        _key: string;
      }
    | {
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }>;
        layout?: "grid2" | "grid3" | "row";
        caption?: string;
        _type: "imageGallery";
        _key: string;
      }
    | {
        style?: "line" | "ornament" | "space";
        _type: "divider";
        _key: string;
      }
    | {
        url?: string;
        caption?: string;
        _type: "videoEmbed";
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
  relatedProject?: ProjectReference;
  relatedPosts?: Array<
    {
      _key: string;
    } & JournalEntryReference
  >;
};

export type JournalPage = {
  _id: string;
  _type: "journalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  stickyCtaLabel?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  formIntroNote?: string;
  formProjectTypeOptions?: Array<string>;
  formLocationOptions?: Array<string>;
  formBudgetOptions?: Array<string>;
  formTimelineOptions?: Array<string>;
  formSourceOptions?: Array<string>;
  whatToExpectEyebrow?: string;
  whatToExpectHeadline?: string;
  whatToExpectContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  postInquiryRoadmap?: Array<{
    title?: string;
    body?: string;
    timeEstimate?: string;
    _type: "roadmapStep";
    _key: string;
  }>;
  schedulingLink?: string;
  schedulingLinkLabel?: string;
  availabilityNote?: string;
  note?: string;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  categoryOrder?: Array<string>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  secondaryCta?: CtaBlock;
  note?: string;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  stickyCtaLabel?: string;
  servicesListEyebrow?: string;
  servicesListHeadline?: string;
  servicesListSubhead?: string;
  builderRealtorSection?: {
    eyebrow?: string;
    headline?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    forBuildersText?: string;
    forRealtorsText?: string;
    forContractorsText?: string;
    cta?: CtaBlock;
  };
  serviceAreaSection?: {
    eyebrow?: string;
    headline?: string;
    description?: string;
  };
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  note?: string;
};

export type ProcessPage = {
  _id: string;
  _type: "processPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  faqSectionEyebrow?: string;
  faqSectionHeadline?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  note?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  storyEyebrow?: string;
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  staciPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  staciAttribution?: string;
  backgroundLine?: string;
  serviceAreaMention?: string;
  philosophyEyebrow?: string;
  philosophyHeadline?: string;
  personalEyebrow?: string;
  personalHeadline?: string;
  personalIntro?: string;
  currentlyList?: Array<{
    label?: string;
    value?: string;
    _type: "currentlyRow";
    _key: string;
  }>;
  rapidFire?: Array<{
    prompt?: string;
    answer?: string;
    _type: "rapidFireRow";
    _key: string;
  }>;
  localSpots?: Array<{
    name?: string;
    note?: string;
    _type: "localSpotRow";
    _key: string;
  }>;
  beyondDesign?: string;
  candidPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  stats?: Array<{
    number?: number;
    suffix?: string;
    label?: string;
    _type: "statItem";
    _key: string;
  }>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  heroPrimaryCta?: CtaBlock;
  heroSecondaryCta?: CtaBlock;
  heroRotatingWords?: Array<string>;
  heroScriptAccent?: string;
  meetStaciPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  meetStaciEyebrow?: string;
  meetStaciHeadline?: string;
  meetStaciContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  meetStaciCta?: CtaBlock;
  featuredWorkEyebrow?: string;
  featuredWorkHeadline?: string;
  featuredWorkSubhead?: string;
  featuredWorkCta?: CtaBlock;
  featuredJournalEyebrow?: string;
  featuredJournalHeadline?: string;
  featuredJournalSubhead?: string;
  featuredJournalCta?: CtaBlock;
  processPreviewEyebrow?: string;
  processPreviewHeadline?: string;
  processPreviewSubhead?: string;
  processPreviewCta?: CtaBlock;
  featuredTestimonial?: TestimonialReference;
  testimonialsEyebrow?: string;
  testimonialsHeadline?: string;
  testimonialsScriptAccent?: string;
  testimonialsSubhead?: string;
  testimonialsToShow?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  testimonialsAttribution?: string;
  servicesGridEyebrow?: string;
  servicesGridHeadline?: string;
  servicesGridScriptAccent?: string;
  servicesGridSubhead?: string;
  servicesGridCta?: CtaBlock;
  servicesGridFootnote?: string;
  serviceAreaCue?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  date?: string;
  source?: "Facebook" | "Google" | "Houzz" | "Direct (email or text)" | "Other";
  location?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
  relatedProject?: ProjectReference;
  sourceType?: "Google" | "Facebook" | "Houzz" | "Direct";
  reviewUrl?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  metaTitle?: string;
  metaDescription?: string;
  location?: string;
  roomType?:
    | "livingRoom"
    | "bedroom"
    | "kitchen"
    | "diningRoom"
    | "office"
    | "wholeHome"
    | "multipleRooms"
    | "other";
  designStyle?:
    | "modernTraditional"
    | "transitional"
    | "modernCoastal"
    | "modernFarmhouse"
    | "modernOrganic"
    | "eclectic"
    | "midCentury"
    | "other";
  year?: number;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  beforeAfters?: Array<{
    beforeImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    afterImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    caption?: string;
    _type: "beforeAfterPair";
    _key: string;
  }>;
  briefSummary?: string;
  briefLine?: string;
  designCall?: string;
  introStory?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              openInNewTab?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              vendor?: string;
              url?: string;
              _type: "sourcedFrom";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        decisionLine?: string;
        _type: "image";
        _key: string;
      }
  >;
  servicesUsed?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedTestimonial?: TestimonialReference;
  displayOrder?: number;
  featured?: boolean;
  stickyCtaLabel?: string;
  publishedAt?: string;
  orderRank?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ShopCollectionReference
  | ShopItem
  | SanityImageCrop
  | SanityImageHotspot
  | ShopCollection
  | Slug
  | PressItem
  | JournalCategory
  | ServiceReference
  | ProcessStep
  | PhilosophyPoint
  | FaqItem
  | StudioPlaybook
  | StudioNotes
  | StudioGuide
  | BudgetCalculator
  | LeadMagnetReference
  | StyleQuiz
  | SanityFileAssetReference
  | LeadMagnet
  | Service
  | PressPage
  | PrivacyPage
  | ResourcesPage
  | GiftPage
  | ShopPage
  | FaqItemReference
  | EDesignPage
  | HomePageReference
  | AboutPageReference
  | ProcessPageReference
  | ServicesPageReference
  | FaqPageReference
  | ContactPageReference
  | JournalPageReference
  | JournalEntryReference
  | CtaBlock
  | NotFoundPage
  | PortfolioPage
  | SiteSettings
  | JournalCategoryReference
  | ProjectReference
  | JournalEntry
  | JournalPage
  | ContactPage
  | FaqPage
  | ServicesPage
  | ProcessPage
  | AboutPage
  | TestimonialReference
  | HomePage
  | Testimonial
  | Project
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
