/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type Redirect = {
  _id: string;
  _type: 'redirect';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from?: string;
  to?: string;
  permanent?: boolean;
  note?: string;
};

export type TrashedItem = {
  _id: string;
  _type: 'trashedItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  originalType?: string;
  originalId?: string;
  deletedAt?: string;
  payload?: string;
};

export type ServiceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'service';
};

export type ProcessStep = {
  _id: string;
  _type: 'processStep';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stepNumber?: number;
  title?: string;
  timeEstimate?: string;
  shortDescription?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  features?: Array<string>;
  tierNote?: string;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  orderRank?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: string;
  priceNumeric?: number;
  shortDescription?: string;
  features?: Array<string>;
  bestFor?: string;
  featuredImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  longDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  displayOrder?: number;
  showOnHomepage?: boolean;
  ctaLabel?: string;
  badge?: string;
  orderRank?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type PhilosophyPoint = {
  _id: string;
  _type: 'philosophyPoint';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  displayOrder?: number;
  orderRank?: string;
};

export type FaqItem = {
  _id: string;
  _type: 'faqItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h4';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  category?: 'Pricing & Cost' | 'The Process' | 'Logistics' | 'Service Area' | 'Getting Started';
  displayOrder?: number;
  alsoShowOnProcessPage?: boolean;
};

export type HomePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'homePage';
};

export type AboutPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'aboutPage';
};

export type ProcessPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'processPage';
};

export type ServicesPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'servicesPage';
};

export type EDesignPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'eDesignPage';
};

export type FaqPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqPage';
};

export type ContactPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'contactPage';
};

export type PortfolioPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'portfolioPage';
};

export type PrivacyPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'privacyPage';
};

export type PageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'page';
};

export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type Announcement = {
  _id: string;
  _type: 'announcement';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTitle?: string;
  enabled?: boolean;
  format?: 'bar' | 'popup';
  tone?: 'info' | 'highlight' | 'urgent';
  heading?: string;
  message?: string;
  link?: NavLink;
  showFrom?: string;
  showUntil?: string;
  placement?: 'all' | 'only' | 'except';
  pages?: ArrayOf<
    | HomePageReference
    | AboutPageReference
    | ProcessPageReference
    | ServicesPageReference
    | EDesignPageReference
    | FaqPageReference
    | ContactPageReference
    | PortfolioPageReference
    | PrivacyPageReference
    | PageReference
    | ProjectReference
  >;
  frequency?: 'once' | 'session' | 'always';
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  linkType?: 'internal' | 'external' | 'custom';
  internalPage?:
    | HomePageReference
    | AboutPageReference
    | ProcessPageReference
    | ServicesPageReference
    | EDesignPageReference
    | FaqPageReference
    | ContactPageReference
    | PortfolioPageReference
    | PrivacyPageReference
    | PageReference
    | ProjectReference;
  externalUrl?: string;
  href?: string;
};

export type StudioPlaybook = {
  _id: string;
  _type: 'studioPlaybook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  guides?: Array<{
    title?: string;
    summary?: string;
    sections?: Array<{
      heading?: string;
      tone?: 'default' | 'primary' | 'positive' | 'caution';
      body?: string;
      bullets?: Array<string>;
      links?: Array<{
        label?: string;
        url?: string;
        _type: 'playbookLink';
        _key: string;
      }>;
      _type: 'playbookSection';
      _key: string;
    }>;
    _type: 'playbookGuide';
    _key: string;
  }>;
};

export type StudioNotes = {
  _id: string;
  _type: 'studioNotes';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessSummary?: string;
  idealClient?: string;
  voiceSummary?: string;
  wordsToAvoid?: Array<string>;
};

export type StudioGuide = {
  _id: string;
  _type: 'studioGuide';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guideTitle?: string;
  guideIntro?: string;
  studioMap?: Array<{
    area?: string;
    description?: string;
    _type: 'mapRow';
    _key: string;
  }>;
  howTos?: Array<{
    title?: string;
    steps?: Array<string>;
    _type: 'howTo';
    _key: string;
  }>;
  tips?: Array<{
    heading?: string;
    tone?: 'default' | 'primary' | 'caution' | 'positive';
    body?: string;
    _type: 'tip';
    _key: string;
  }>;
};

export type NotFoundPage = {
  _id: string;
  _type: 'notFoundPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  eyebrow?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaHref?: string;
};

export type BusinessInfo = {
  _id: string;
  _type: 'businessInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  city?: string;
  state?: string;
  serviceRegion?: string;
  serviceAreas?: Array<string>;
  travelFees?: Array<{
    distanceLabel?: string;
    fee?: string;
    _type: 'travelFeeTier';
    _key: string;
  }>;
  availabilityStatus?: string;
  geoLat?: number;
  geoLng?: number;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  primaryCtaLabel?: string;
  headerTagline?: string;
  email?: string;
  phone?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  navItems?: Array<
    | ({
        _key: string;
      } & NavLink)
    | {
        label?: string;
        links?: Array<
          {
            _key: string;
          } & NavLink
        >;
        _type: 'navGroup';
        _key: string;
      }
  >;
  footerColumns?: Array<{
    title?: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    _type: 'footerColumn';
    _key: string;
  }>;
  legalNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  headerCta?: {
    show?: boolean;
    label?: string;
    link?: NavLink;
  };
  showEmail?: boolean;
  showSocials?: boolean;
  showFooterSocials?: boolean;
  availabilityStatus?: string;
  serviceAreas?: Array<string>;
  travelFees?: Array<{
    distanceLabel?: string;
    fee?: string;
    _type: 'travelFeeTier';
    _key: string;
  }>;
  socialInstagram?: string;
  socialFacebook?: string;
  instagramFeedHeadline?: string;
  instagramFeedScriptAccent?: string;
  instagramFeedSubhead?: string;
  instagramFeedLinkLabel?: string;
  instagramFeedOnHome?: boolean;
  instagramFeedOnContact?: boolean;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  footerCredit?: string;
  footerCreditUrl?: string;
  newsletter?: {
    enabled?: boolean;
    providerLabel?: string;
    formActionUrl?: string;
    audienceId?: string;
    heading?: string;
    blurb?: string;
    buttonLabel?: string;
    successMessage?: string;
    consentNote?: string;
  };
  googleBusinessUrl?: string;
  googleRating?: number;
  googleReviewCount?: number;
  googleWriteReviewUrl?: string;
  googlePlaceId?: string;
  googleReviewsUpdatedAt?: string;
  reviewsNote?: string;
  sectionVisibility?: {
    showPortfolio?: boolean;
    showJournal?: boolean;
    showShop?: boolean;
    showEDesign?: boolean;
    showGiftCertificates?: boolean;
    showPress?: boolean;
    showResources?: boolean;
    showGuides?: boolean;
    showStyleQuiz?: boolean;
    showBudgetCalculator?: boolean;
  };
  satisfactionGuarantee?: string;
};

export type EDesignSectionMarker = {
  _type: 'eDesignSectionMarker';
  section?: 'intro' | 'howItWorks' | 'whatsIncluded' | 'tiers' | 'faq';
};

export type ProcessSectionMarker = {
  _type: 'processSectionMarker';
  section?: 'hero' | 'steps' | 'faq' | 'finalCta';
};

export type ServicesSectionMarker = {
  _type: 'servicesSectionMarker';
  section?: 'hero' | 'servicesList' | 'builders' | 'serviceArea' | 'guarantee' | 'finalCta';
};

export type HomeSectionMarker = {
  _type: 'homeSectionMarker';
  section?:
    | 'hero'
    | 'meetStaci'
    | 'featuredWork'
    | 'testimonials'
    | 'processPreview'
    | 'roomStory'
    | 'services'
    | 'featuredJournal'
    | 'press'
    | 'instagram'
    | 'serviceAreaCue'
    | 'finalCta';
};

export type AboutSectionMarker = {
  _type: 'aboutSectionMarker';
  section?:
    'hero' | 'story' | 'philosophy' | 'personal' | 'press' | 'stats' | 'kindWords' | 'finalCta';
};

export type InstagramSection = {
  _type: 'instagramSection';
  heading?: string;
  subhead?: string;
};

export type SpacerSection = {
  _type: 'spacerSection';
  variant?: 'ornament' | 'line' | 'space';
};

export type VideoSection = {
  _type: 'videoSection';
  url?: string;
  heading?: string;
  caption?: string;
};

export type CtaBandSection = {
  _type: 'ctaBandSection';
  eyebrow?: string;
  headline?: string;
  scriptAccent?: string;
  subhead?: string;
  cta?: CtaBlock;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type StatSection = {
  _type: 'statSection';
  heading?: string;
  stats?: Array<{
    number?: number;
    suffix?: string;
    label?: string;
    _type: 'statItem';
    _key: string;
  }>;
};

export type QuoteSection = {
  _type: 'quoteSection';
  quote?: string;
  attribution?: string;
  detail?: string;
};

export type GallerySection = {
  _type: 'gallerySection';
  heading?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
    _key: string;
  }>;
  columns?: 2 | 3 | 4;
};

export type ImageTextSection = {
  _type: 'imageTextSection';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  imageSide?: 'left' | 'right';
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: CtaBlock;
};

export type RichTextSection = {
  _type: 'richTextSection';
  eyebrow?: string;
  heading?: string;
  scriptAccent?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  width?: 'normal' | 'narrow';
  align?: 'left' | 'center';
};

export type HeroSection = {
  _type: 'heroSection';
  eyebrow?: string;
  headline?: string;
  scriptAccent?: string;
  subhead?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  primaryCta?: CtaBlock;
  secondaryCta?: CtaBlock;
  size?: 'tall' | 'short';
};

export type PrivacyPage = {
  _id: string;
  _type: 'privacyPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  additionalSections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
};

export type PortfolioPage = {
  _id: string;
  _type: 'portfolioPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  beforeAfterSeoTitle?: string;
  beforeAfterSeoDescription?: string;
  beforeAfterEyebrow?: string;
  beforeAfterHeadline?: string;
  beforeAfterSubhead?: string;
  additionalSections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
};

export type FaqItemReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqItem';
};

export type EDesignPage = {
  _id: string;
  _type: 'eDesignPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  pageBuilder?: Array<
    | ({
        _key: string;
      } & EDesignSectionMarker)
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  howItWorks?: Array<{
    stepNumber?: number;
    title?: string;
    body?: string;
    _type: 'howItWorksStep';
    _key: string;
  }>;
  whatsIncluded?: Array<string>;
  tiers?: Array<{
    name?: string;
    price?: string;
    priceNumeric?: number;
    features?: Array<string>;
    bestFor?: string;
    ctaLabel?: string;
    _type: 'eDesignTier';
    _key: string;
  }>;
  faqRefs?: Array<
    {
      _key: string;
    } & FaqItemReference
  >;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type CtaBlock = {
  _type: 'ctaBlock';
  label?: string;
  linkType?: 'internal' | 'external' | 'email' | 'phone';
  internalLink?:
    | HomePageReference
    | AboutPageReference
    | ProcessPageReference
    | ServicesPageReference
    | FaqPageReference
    | ContactPageReference
    | PageReference;
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  addToMainNav?: boolean;
  navGroup?: 'top' | 'services' | 'resources';
  navLabel?: string;
  addToFooter?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  formIntroNote?: string;
  formProjectTypeOptions?: Array<string>;
  formLocationOptions?: Array<string>;
  formBudgetOptions?: Array<string>;
  formTimelineOptions?: Array<string>;
  formSourceOptions?: Array<string>;
  whatToExpectEyebrow?: string;
  whatToExpectHeadline?: string;
  whatToExpectContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  postInquiryRoadmap?: Array<{
    title?: string;
    body?: string;
    timeEstimate?: string;
    _type: 'roadmapStep';
    _key: string;
  }>;
  schedulingLink?: string;
  schedulingLinkLabel?: string;
  availabilityNote?: string;
  note?: string;
  additionalSections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
};

export type FaqPage = {
  _id: string;
  _type: 'faqPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  categoryOrder?: Array<string>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  secondaryCta?: CtaBlock;
  note?: string;
  additionalSections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
};

export type ServicesPage = {
  _id: string;
  _type: 'servicesPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  pageBuilder?: Array<
    | ({
        _key: string;
      } & ServicesSectionMarker)
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  stickyCtaLabel?: string;
  servicesListEyebrow?: string;
  servicesListHeadline?: string;
  servicesListSubhead?: string;
  builderRealtorSection?: {
    eyebrow?: string;
    headline?: string;
    description?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: null;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    forBuildersText?: string;
    forRealtorsText?: string;
    forContractorsText?: string;
    cta?: CtaBlock;
  };
  serviceAreaSection?: {
    eyebrow?: string;
    headline?: string;
    description?: string;
  };
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  note?: string;
};

export type ProcessPage = {
  _id: string;
  _type: 'processPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  pageBuilder?: Array<
    | ({
        _key: string;
      } & ProcessSectionMarker)
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  faqSectionEyebrow?: string;
  faqSectionHeadline?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  note?: string;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  pageBuilder?: Array<
    | ({
        _key: string;
      } & AboutSectionMarker)
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  storyEyebrow?: string;
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  staciPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  staciAttribution?: string;
  backgroundLine?: string;
  serviceAreaMention?: string;
  philosophyEyebrow?: string;
  philosophyHeadline?: string;
  personalEyebrow?: string;
  personalHeadline?: string;
  personalIntro?: string;
  currentlyList?: Array<{
    label?: string;
    value?: string;
    _type: 'currentlyRow';
    _key: string;
  }>;
  rapidFire?: Array<{
    prompt?: string;
    answer?: string;
    _type: 'rapidFireRow';
    _key: string;
  }>;
  localSpots?: Array<{
    name?: string;
    note?: string;
    _type: 'localSpotRow';
    _key: string;
  }>;
  beyondDesign?: string;
  candidPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  stats?: Array<{
    number?: number;
    suffix?: string;
    label?: string;
    _type: 'statItem';
    _key: string;
  }>;
  kindWordsShow?: boolean;
  kindWordsEyebrow?: string;
  kindWordsHeadline?: string;
  kindWordsScriptAccent?: string;
  kindWordsSubhead?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type TestimonialReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'testimonial';
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HomeSectionMarker)
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & InstagramSection)
  >;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  heroPortrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroPrimaryCta?: CtaBlock;
  heroSecondaryCta?: CtaBlock;
  heroRotatingWords?: Array<string>;
  heroScriptAccent?: string;
  meetStaciPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  meetStaciEyebrow?: string;
  meetStaciHeadline?: string;
  meetStaciContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  meetStaciCta?: CtaBlock;
  featuredWorkEyebrow?: string;
  featuredWorkHeadline?: string;
  featuredWorkSubhead?: string;
  featuredWorkCta?: CtaBlock;
  featuredJournalEyebrow?: string;
  featuredJournalHeadline?: string;
  featuredJournalSubhead?: string;
  featuredJournalCta?: CtaBlock;
  processPreviewEyebrow?: string;
  processPreviewHeadline?: string;
  processPreviewSubhead?: string;
  processPreviewCta?: CtaBlock;
  roomStoryShow?: boolean;
  roomStoryHeadline?: string;
  roomStoryScriptAccent?: string;
  roomStoryIntro?: string;
  featuredTestimonial?: TestimonialReference;
  testimonialsEyebrow?: string;
  testimonialsHeadline?: string;
  testimonialsScriptAccent?: string;
  testimonialsSubhead?: string;
  testimonialsToShow?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  testimonialsAttribution?: string;
  servicesGridEyebrow?: string;
  servicesGridHeadline?: string;
  servicesGridScriptAccent?: string;
  servicesGridSubhead?: string;
  servicesGridCta?: CtaBlock;
  servicesGridFootnote?: string;
  serviceAreaCue?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Testimonial = {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  date?: string;
  source?: 'Facebook' | 'Google' | 'Houzz' | 'Direct (email or text)' | 'Other';
  location?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  featured?: boolean;
  relatedProject?: ProjectReference;
  sourceType?: 'Google' | 'Facebook' | 'Houzz' | 'Direct';
  reviewUrl?: string;
  rating?: 5 | 4 | 3 | 2 | 1;
  hideOnWebsite?: boolean;
  googleReviewId?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  metaTitle?: string;
  metaDescription?: string;
  location?: string;
  roomType?:
    | 'livingRoom'
    | 'bedroom'
    | 'kitchen'
    | 'diningRoom'
    | 'office'
    | 'wholeHome'
    | 'multipleRooms'
    | 'other';
  designStyle?:
    | 'modernTraditional'
    | 'transitional'
    | 'modernCoastal'
    | 'modernFarmhouse'
    | 'modernOrganic'
    | 'eclectic'
    | 'midCentury'
    | 'other';
  year?: number;
  houseDescription?: string;
  scopeLine?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
    _key: string;
  }>;
  beforeAfters?: Array<{
    beforeImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    afterImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    caption?: string;
    _type: 'beforeAfterPair';
    _key: string;
  }>;
  briefSummary?: string;
  briefLine?: string;
  designCall?: string;
  introStory?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h2' | 'h3' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<
          | {
              href?: string;
              openInNewTab?: boolean;
              _type: 'link';
              _key: string;
            }
          | {
              vendor?: string;
              url?: string;
              _type: 'sourcedFrom';
              _key: string;
            }
        >;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        decisionLine?: string;
        _type: 'image';
        _key: string;
      }
  >;
  servicesUsed?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedTestimonial?: TestimonialReference;
  displayOrder?: number;
  featured?: boolean;
  stickyCtaLabel?: string;
  consent?: {
    photos?: boolean;
    price?: boolean;
    review?: boolean;
  };
  publishedAt?: string;
  orderRank?: string;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Redirect
  | TrashedItem
  | ServiceReference
  | ProcessStep
  | SanityImageAssetReference
  | Service
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | PhilosophyPoint
  | FaqItem
  | HomePageReference
  | AboutPageReference
  | ProcessPageReference
  | ServicesPageReference
  | EDesignPageReference
  | FaqPageReference
  | ContactPageReference
  | PortfolioPageReference
  | PrivacyPageReference
  | PageReference
  | ProjectReference
  | Announcement
  | NavLink
  | StudioPlaybook
  | StudioNotes
  | StudioGuide
  | NotFoundPage
  | BusinessInfo
  | SiteSettings
  | EDesignSectionMarker
  | ProcessSectionMarker
  | ServicesSectionMarker
  | HomeSectionMarker
  | AboutSectionMarker
  | InstagramSection
  | SpacerSection
  | VideoSection
  | CtaBandSection
  | StatSection
  | QuoteSection
  | GallerySection
  | ImageTextSection
  | RichTextSection
  | HeroSection
  | PrivacyPage
  | PortfolioPage
  | FaqItemReference
  | EDesignPage
  | CtaBlock
  | Page
  | ContactPage
  | FaqPage
  | ServicesPage
  | ProcessPage
  | AboutPage
  | TestimonialReference
  | HomePage
  | Testimonial
  | Project
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
