// eslint.config.js: flat config (ESLint 9+). Family standard, modelled on
// presacademy's config. Minimal, low-noise ruleset: the recommended bases only,
// with a few rules tuned so the existing codebase passes without mass edits.
//
// Run with `npm run lint` (CI runs it after `astro check`). Type errors are
// astro check's job, not eslint's; this catches the plain mistakes the
// compiler is happy with (unused imports, unsafe globals, duplicate keys).

import tseslint from 'typescript-eslint';
import eslintPluginAstro from 'eslint-plugin-astro';

/** @type {import('eslint').Linter.Config[]} */
export default [
  // -- Global ignores -------------------------------------------------------
  {
    ignores: [
      'dist/**',
      '.astro/**',
      '.wrangler/**',
      '.studio-dist/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'tmp/**',
      // Generated by `npm run typegen`; never hand-edited.
      'src/lib/sanity.types.ts',
      // Wrangler's generated Worker bindings.
      'worker-configuration.d.ts',
    ],
  },

  // -- TypeScript sources (ts/tsx, plus the .mjs scripts) -------------------
  // NOTE: the Astro processor creates virtual .ts paths like src/Foo.astro/*.ts.
  // These match src/**/*.ts, so the Astro override block below corrects rule
  // severity for those virtual paths.
  ...tseslint.configs.recommended.map((cfg) => ({
    ...cfg,
    files: ['src/**/*.{ts,tsx}', 'tests/**/*.ts', 'scripts/**/*.mjs', '*.ts', '*.mjs'],
  })),

  // -- Rule overrides for TS/mjs (non-Astro virtual paths) ------------------
  {
    files: ['src/**/*.{ts,tsx}', 'tests/**/*.ts', 'scripts/**/*.mjs', '*.ts', '*.mjs'],
    // Exclude Astro virtual paths; they are handled in the Astro override below.
    ignores: ['**/*.astro/**'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      // 'any' is used intentionally in several Sanity-typed utilities.
      '@typescript-eslint/no-explicit-any': 'off',
      // Unused vars: warn; leading-underscore names are intentional skips.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      // Allow require() in .mjs scripts that reach Node built-ins via CJS interop.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  // -- Astro sources --------------------------------------------------------
  // eslint-plugin-astro ships its own parser; spread the full recommended
  // config array so the parser, processor, and rules all land correctly.
  ...eslintPluginAstro.configs.recommended,

  {
    files: ['src/**/*.astro'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      // Astro imports are often component-only (used in the template, not in
      // script scope); the parser may not track usage through the template.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },

  // -- Astro virtual script paths (.astro/*.ts created by the processor) ----
  // These virtual files match src/**/*.ts but hold raw <script> block content.
  {
    files: ['**/*.astro/**'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      // Astro <script> blocks use var for hoisting; these files cannot be edited.
      'no-var': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
];
